name: default
on: [push]
runs-on: ${{ matrix.virtual-environment }}
strategy:
  matrix:
    virtual-environment: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
jobs:
  test1:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: File informations
        run: |
          md5sum *.yml
          stat *.yml
      - # Expecting: build ok
        # Actual behavior: build ok
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
        continue-on-error: true
      - # Expecting: 'invalid reference format: repository name must be lowercase'
        # Actual behavior:
        name: Build container(s) in docker-compose.fails.yml
        run: docker-compose -f docker-compose.fails.yml build
        continue-on-error: true
      - # Expecting: build ok
        # Actual behavior:
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
        continue-on-error: true
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '8'
      - name: Install npm packages
        run: npm install --prefix node
      - name: Build docker-compose.yml
        run: npm start --prefix node "../docker-compose.fails-node.yml" "${{ github.repository }}"
      - name: File informations
        run: |
          md5sum *.yml
          stat *.yml
      - # Expecting: build ok
        # Actual behavior: build ok
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
        continue-on-error: true
      - # Expecting: 'invalid reference format: repository name must be lowercase'
        # Actual behavior:
        name: Build container(s) in docker-compose.fails.yml
        run: docker-compose -f docker-compose.fails.yml build
        continue-on-error: true
      - # Expecting: 'invalid reference format: repository name must be lowercase'
        # Actual behavior:
        name: Build container(s) in docker-compose.fails-node.yml
        run: docker-compose -f docker-compose.fails-node.yml build
        continue-on-error: true
      - # Expecting: build ok
        # Actual behavior:
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
        continue-on-error: true
  test2:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: File informations
        run: |
          md5sum *.yml
          stat *.yml
      - name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
        continue-on-error: true
        # Expecting: 'invalid reference format: repository name must be lowercase'
        # Actual behavior as expected
      - name: Build container(s) in docker-compose.fails.yml
        run: docker-compose -f docker-compose.fails.yml build
        continue-on-error: true
