name: "default"
on:
  push:
    branches:
      - master
jobs:
  ubuntu1604:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container images
        run: docker-compose build
  ubuntu1804:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container images
        run: docker-compose build
  ubuntu2004:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container images
        run: docker-compose build
