name: "default"
on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 4 * * *"
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '8' # TODO: update to 14 (LTS)
      - name: Install npm packages
        run: npm install --prefix node
      - name: Build docker-compose.yml
        run: npm start --prefix node "../docker-compose.fails.yml" "${{ github.repository }}"
      - name: Show docker-compose.yml
        run: cat docker-compose.yml
      - name: Diff docker-compose.yml
        run: diff docker-compose.works.yml docker-compose.fails.yml
      - name: Build container images
        run: docker-compose build
