name: "default"
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
      - name: Build container(s) in docker-compose.fails.yml
        run: docker-compose -f docker-compose.fails.yml build
