name: default
on: [push]
jobs:
  without-node:
    runs-on: ${{ matrix.virtual-environment }}
    strategy:
      matrix:
        virtual-environment: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: File informations
        run: |
          md5sum *.yml
          stat *.yml
      - # Expecting: build ok
        # Actual behavior: build ok
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
      - # Expecting: 'invalid reference format: repository name must be lowercase'
        # Actual behavior: 'invalid reference format: repository name must be lowercase'
        name: Build container(s) in docker-compose.fails.yml
        run: docker-compose -f docker-compose.fails.yml build
        continue-on-error: true
      - # Expecting: build ok
        # Actual behavior: build ok
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
  with-node:
    runs-on: ${{ matrix.virtual-environment }}
    strategy:
      matrix:
        virtual-environment: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        node-version: [8, 10, 12, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm package(s)
        run: npm install js-yaml
      - name: File informations
        run: |
          md5sum *.yml
          stat *.yml
      - # Expecting: build ok
        # Actual behavior: build ok
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
      - # Expecting: 'invalid reference format: repository name must be lowercase'
        # Actual behavior: 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
        name: Build container(s) in docker-compose.fails.yml
        run: docker-compose -f docker-compose.fails.yml build
        continue-on-error: true
      - # Expecting: build ok
        # Actual behavior: build ok
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml build
