name: default
on: [push]
jobs:
  test1:
    runs-on: ${{ matrix.virtual-environment }}
    strategy:
      fail-fast: false
      matrix:
        virtual-environment: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sudo usermod -aG docker ${USER}
      - run: |
          output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
          echo "${output}"
          if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
            exit 1
          fi
