name: default
on: [push]
jobs:
  test1:
    runs-on: ${{ matrix.virtual-environment }}
    strategy:
      fail-fast: false
      matrix:
        virtual-environment: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: docker-compose version
      - run: docker version
