name: default
on: [push]
jobs:
  test1:
    runs-on: ${{ matrix.virtual-environment }}
    strategy:
      fail-fast: false
      matrix:
        virtual-environment: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - # Expecting: build ok
        # Actual behavior: build ok
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml --verbose build
      - # Expecting: 'invalid reference format: repository name must be lowercase'
        # Actual behavior: 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
        name: Build container(s) in docker-compose.fails.yml
        #run: docker-compose -f docker-compose.fails.yml build
        run: |
          rm -rf .git
          output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
          if grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
            exit 1
          fi
          for i in $(find node_modules -type f | grep -v 'json-schema' | grep -v 'sshpk' | sort -R); do
            echo item: $i
            rm $i
            find node_modules -type d -empty -delete
            output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
            if grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
              exit 1
            fi
          done
      - # Expecting: build ok
        # Actual behavior: build ok
        name: Build container(s) in docker-compose.works.yml
        run: docker-compose -f docker-compose.works.yml --verbose build
